In [1]:
import pandas as pd

In [14]:
df_ea = pd.read_csv('/mnt/d/幽门螺旋杆菌/Script/分析结果/2-变异统计/output/比较东亚和全球/var/East_Asia.var.csv')
df_ea

,CHROM,POS,REF,ALT,AC,Source,Freq,Type,Special
0,NC_000915.1,5,T,C,1,East_Asia,UltraRare,SNV,Singleton
1,NC_000915.1,61,T,G,1,East_Asia,UltraRare,SNV,Singleton
2,NC_000915.1,68,T,G,1,East_Asia,UltraRare,SNV,Singleton
3,NC_000915.1,73,A,ATTTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATT...,1,East_Asia,UltraRare,Indel,Singleton
4,NC_000915.1,75,TAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGT...,AGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTG...,1,East_Asia,UltraRare,Indel,Singleton
...,...,...,...,...,...,...,...,...,...
1412628,NC_000915.1,1667851,C,T,2,East_Asia,Rare,SNV,Doubleton
1412629,NC_000915.1,1667854,C,T,1,East_Asia,UltraRare,SNV,Singleton
1412630,NC_000915.1,1667855,C,CT,6,East_Asia,Rare,Indel,NaN
1412631,NC_000915.1,1667856,T,TC,18,East_Asia,LowFreq,Indel,NaN
1412632,NC_000915.1,1667857,T,C,3,East_Asia,Rare,SNV,NaN

In [18]:
df_ea.loc[(df_ea['Freq'] == 'Common') & (df_ea['Type'] == 'SNV')]  # 过滤出频率为common且类型为SNP的变异
# 按照POS	REF	ALT构建唯一标识符
df_ea['ID'] = df_ea['POS'].astype(str) + '_' + df_ea['REF'] + '_' + df_ea['ALT']
df_ea

,CHROM,POS,REF,ALT,AC,Source,Freq,Type,Special,ID
0,NC_000915.1,5,T,C,1,East_Asia,UltraRare,SNV,Singleton,5_T_C
1,NC_000915.1,61,T,G,1,East_Asia,UltraRare,SNV,Singleton,61_T_G
2,NC_000915.1,68,T,G,1,East_Asia,UltraRare,SNV,Singleton,68_T_G
3,NC_000915.1,73,A,ATTTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATT...,1,East_Asia,UltraRare,Indel,Singleton,73_A_ATTTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAG...
4,NC_000915.1,75,TAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGT...,AGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTG...,1,East_Asia,UltraRare,Indel,Singleton,75_TAGTGATTAGTGATTAGTGATTAGTGATTAGTGATTAGTGATT...
...,...,...,...,...,...,...,...,...,...,...
1412628,NC_000915.1,1667851,C,T,2,East_Asia,Rare,SNV,Doubleton,1667851_C_T
1412629,NC_000915.1,1667854,C,T,1,East_Asia,UltraRare,SNV,Singleton,1667854_C_T
1412630,NC_000915.1,1667855,C,CT,6,East_Asia,Rare,Indel,NaN,1667855_C_CT
1412631,NC_000915.1,1667856,T,TC,18,East_Asia,LowFreq,Indel,NaN,1667856_T_TC
1412632,NC_000915.1,1667857,T,C,3,East_Asia,Rare,SNV,NaN,1667857_T_C

In [19]:
# 根据唯一标识符，统计如下，获得csv文件：
# 首先去重，基于唯一标识符ID
df_unique = df_ea.drop_duplicates(subset=['ID'])

# 创建统计结果列表
stats_data = []

# 统计频率类别 - 基于去重后的唯一变异
freq_counts = df_unique['Freq'].value_counts()
for freq in ['UltraRare', 'Rare', 'LowFreq', 'Common']:
    count = freq_counts.get(freq, 0)
    stats_data.append(['Frequency', freq, count, 'East_Asia'])

# 统计类型 - 基于去重后的唯一变异
type_counts = df_unique['Type'].value_counts()
for var_type in ['SNV', 'Indel']:
    count = type_counts.get(var_type, 0)
    stats_data.append(['Type', var_type, count, 'East_Asia'])

# 统计特殊类别 - 基于去重后的唯一变异
if 'AC' in df_unique.columns:
    singleton_count = len(df_unique[df_unique['AC'] == 1])
    doubleton_count = len(df_unique[df_unique['AC'] == 2])
else:
    # 如果没有AC列，尝试从Special列获取
    if 'Special' in df_unique.columns:
        special_counts = df_unique['Special'].value_counts()
        singleton_count = special_counts.get('Singleton', 0)
        doubleton_count = special_counts.get('Doubleton', 0)
    else:
        singleton_count = 0
        doubleton_count = 0

stats_data.append(['Special', 'Singleton', singleton_count, 'East_Asia'])
stats_data.append(['Special', 'Doubleton', doubleton_count, 'East_Asia'])

# 创建DataFrame
stats_df = pd.DataFrame(stats_data, columns=['Category', 'Class', 'Count', 'Source'])

# 保存到CSV文件
output_path = '/mnt/d/幽门螺旋杆菌/Script/分析结果/2-变异统计/output/East_Asia_variant_stats.csv'
stats_df.to_csv(output_path, index=False)

print("基于唯一标识符的统计结果：")
print(stats_df)
print(f"\n统计结果已保存到: {output_path}")

# 显示去重前后的数据量对比
print(f"\n去重前数据量: {len(df_ea)}")
print(f"去重后数据量: {len(df_unique)}")
print(f"唯一变异数量: {df_ea['ID'].nunique()}")

基于唯一标识符的统计结果：
    Category      Class    Count     Source
0  Frequency  UltraRare   426059  East_Asia
1  Frequency       Rare   597759  East_Asia
2  Frequency    LowFreq   221691  East_Asia
3  Frequency     Common   161362  East_Asia
4       Type        SNV  1155857  East_Asia
5       Type      Indel   251014  East_Asia
6    Special  Singleton   425869  East_Asia
7    Special  Doubleton   162366  East_Asia

统计结果已保存到: /mnt/d/幽门螺旋杆菌/Script/分析结果/2-变异统计/output/East_Asia_variant_stats.csv

去重前数据量: 1412633
去重后数据量: 1406871
唯一变异数量: 1406871